if(typeof window.random_array == "undefined"){var random_array = new Array();} if (!window.ActiveXObject){ document.write("<div style=\"text-align: center; margin: 0px auto; width:300px; height:250px; position:relative;\">");document.write("<style type=\"text\/css\"> .yieldLink{ position:absolute; bottom:0px; left:0px; width:14px; height:14px; min-width:14px; max-width:14px; min-height:14px; max-height:14px; color:#FFF; background-color:#4D88D2; text-align:center; font:11px Arial, Tahoma, sans-serif; font-weight:bold; opacity:0.6; filter:alpha(opacity=60); } DIV.yieldLink:hover { cursor:pointer; color:#99ffff; opacity:.9; filter:alpha(opacity=90); } <\/style>"); }var prot = document.location.protocol; var randomy = Math.floor(Math.random()*(1000000000000-9999999999999+1))+9999999999999; var PubID = '6343'; var SiteID='119'; var network = null; var psa = 0; var store = "0"; var keyword = "IstqbExamCertification.com"; var result = null; var resultBlocked = null; var resultServing = null; var blockedURLs = ["porn","topless","fuck","xxx","tits","pussy","nude","xrated","cunt","gangbang","explicit","blowjob","jailbait","nsfw","dead","shot","killed","died","murder","suicide","violence","abused","behead","rape","sex","nipple","gore","porno","carajo","tetas","orgia","mamada","muertos","disparo","muertos","asesinato","suicidio","violencia","abusado","sexo","sesso"]; var approvedURLs = ['istqbexamcertification.com']; var adServingURLs = ['yieldselect.com','ads-by.yieldselect.com']; var googlePage = 'www.istqbexamcertification.com';  var realURL = 1; var iframe = 0; var url = 0; var src = 0;  if (top === self){ var refURL = document.location.hostname; var refURL_full = document.location.href; url = encodeURIComponent(document.location.href); src = 0; } else { var refURL = document.referrer.split('/')[2]; var refURL_full = document.referrer; url = encodeURIComponent(document.location.href); src = encodeURIComponent(document.referrer); }  if(!refURL){ refURL = googlePage ? prot+'//'+googlePage : document.location.hostname; refURL_full = googlePage ? prot+'//'+googlePage : document.location.href; realURL = 0; }  if(iframe == 1 && !src){ refURL = document.location.hostname; refURL_full = document.location.href; src = 'BlankRefServe'; realURL = 0; }  for(var i = 0; i < blockedURLs.length; i++){ if(refURL_full.toLowerCase().match(blockedURLs[i])){ resultBlocked = true; break; }} if(!resultBlocked){ for(var i = 0; i < approvedURLs.length; i++){ if(refURL.toLowerCase().match(approvedURLs[i])){ result = true; break; }} for(var i = 0; i < adServingURLs.length; i++){ if(refURL.toLowerCase().match(adServingURLs[i])){ resultServing = adServingURLs[i]; break; }}  if(result || resultServing){ (function() {var useSSL = 'https:' == document.location.protocol; var src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js'; document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');})();{
										if (typeof window.randomyNum == 'undefined') 
										{
											var randomyNum = 0;
										} else {
											window.randomyNum++;
										}
										var mam = document;
										var acc300x250 = "8223";
										var site300x250 = "14911";
										var zone300x250 = "59842-15";
										mam.writeln("<div id='div-gpt-ad-08375803464502-" + window.randomyNum + "' style='width:300px; height:250px;'>");
										mam.writeln("<script type='text/javascript'>");mam.writeln("googletag.defineSlot('/21533241/IstqbExamCertification.com-(ID:6343)-ROS-300x250', [300, 250], 'div-gpt-ad-08375803464502-'+window.randomyNum).addService(googletag.pubads()); googletag.pubads().enableSyncRendering(); googletag.enableServices(); if(resultServing || realURL == 0){ googletag.pubads().set('page_url', 'istqbexamcertification.com'); } googletag.display('div-gpt-ad-08375803464502-'+window.randomyNum);"); mam.writeln("<\/script>");
										mam.writeln("<\/div>");
                                                                                
                                                                                var _qevents = _qevents || [];
                                                                                (function() {
                                                                                var elem = document.createElement('script');
                                                                                elem.src = (document.location.protocol == 'https:' ? 'https://secure' : 'http://edge') + '.quantserve.com/quant.js';
                                                                                elem.async = true;
                                                                                elem.type = 'text/javascript';
                                                                                var scpt = document.getElementsByTagName('script')[0];
                                                                                scpt.parentNode.insertBefore(elem, scpt);
                                                                                })();
                                                                                _qevents.push({
                                                                                qacct:'p-QAjpCznqPvtcy'
                                                                                }); 
                                                                                
                                                                                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                                                                                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                                                                                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                                                                                })(window,document,'script','//www.google-analytics.com/analytics.js','YSga');
                                                                                YSga('create', 'UA-49158294-3', 'yieldselect.com');
                                                                                YSga('require', 'displayfeatures');
                                                                                YSga('send', 'pageview');
									} }else{ psa = 1;  var dw = document; if(typeof pb300x250 != 'undefined'){ dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="'+prot+'//ads-by.yieldselect.com/tags/' + pb300x250 + '">'); dw.write('<\/scr' + 'ipt>'); } else { dw.write('<script language="JavaScript" type="text/javascript"'); dw.write('src="'+prot+'//ads-by.yieldselect.com/tags/psa/300x250.js">'); dw.write('<\/scr' + 'ipt>'); } } } else {  }if (!window.ActiveXObject){ document.write("<div class=\"yieldLink\"><span><a style=\"color: white; text-decoration: none\" href=\""+prot+"//www.yieldselect.com\/index\/ref\/1\/\" target=\"_blank\">?</a></span></div>"); document.write("<\/div>"); }